version: 3

models:
  - name: stg_prices
    columns:
      - name: start_time_local
        tests:
          - not_null
          - unique
      - name: price_c_kwh
        tests:
          - not_null

  - name: stg_generation_hourly
    description: "Hourly aggregated generation data by energy type (Silver layer)."
    columns:
      - name: hour
        tests:
          - not_null
          - unique
      - name: nuclear_mw
      - name: wind_mw
      - name: hydro_mw
      - name: total_production_mw
      - name: other_generation_mw

  - name: fct_energy_hourly
    description: "Final: Spot prices and generation mix per hour."
    columns:
      - name: start_time_local
        description: "Local time in Helsinki. Guaranteed to be not null."
        tests:
          - not_null
          - unique
      - name: price_c_kwh
      - name: is_negative_price
      - name: nuclear_mw
      - name: wind_mw
      - name: hydro_mw
      - name: other_generation_mw
      - name: total_production_mw
